### ISSUE TITLE
关于白平衡算法

### ISSUE THREAD

**Issue by hey-mu** [cpuimage/AutomaticWhiteBalance#2]
您好，我看您的这篇https://www.cnblogs.com/cpuimage/p/5102567.html博文过来的。
感觉跟这篇博文所说的方法不太一样，您这个自动白平衡算法用的是什么方法呢？
您这个代码没有注释，我刚学还看不太懂，有没有参考文献呢？
谢谢啦

**Comment by cpuimage** [comment]
@hey-mu 主要算法是自研的，没有参考文献，其中一部分思路你可以参阅自动色阶相关的算法。
其他的耐心阅读代码理解。
